### ISSUE TITLE
Could contact you so,

### ISSUE THREAD

**Issue by abhijitgawai** [aniketambore/Flutter-Blockchain#2]
I am student from vit pune. I really want an internship in blockchain. What should i do. I have learnt solidity. What projects should i build?

**Comment by anipy1** [comment]
Hello @abhijitgawai ,

While learning solidity I hope that you created several different programs, like starting from simple Greeter or simple storage programs to more advance level programs. After that what I would like to suggest is, try to link your smart contracts with some ui framework.
In this project I used flutter framework because my aim is to build mobile based cross platform dapps, but you can use any framework, it totally depends on your imagination or what kind of applications you want to develop.

Thank you.

**Comment by abhijitgawai** [comment]
yes i made some programs like https://gist.github.com/abhijitgawai. Thanks a lot. 
What about internships? Thanks a lot in advance
