### ISSUE TITLE
only loading screen appears

### ISSUE THREAD

**Issue by mayankpatidar275** [aniketambore/Flutter-Blockchain#6]
it was all working fine till " truffle migrate "  and  " truffle test " but after " flutter run " its building in my device but showing only hello world and a loading screen. Please help...
My code is same as 
[https://t.co/nXuWUhGfSx](url)

**Comment by anipy1** [comment]
Hello @mayankpatidar275 ,

Verify your `_rpcUrl` variable defined in `contract_linking.dart `.

If you're running the application on your emulator you could simply use this:
![Screenshot486](https://user-images.githubusercontent.com/52826253/182009158-3a51d32b-cb82-438d-905d-f368d1e8d5d3.png)

If you're running the application on your real device, make sure you first  set the **RPC SERVER** url in ganache by going to:
`Settings -> SERVER -> HOSTNAME -> Select <youripaddress-WiFi> -> SAVE AND RESTART` and then paste the appropriate **RPC SERVER** url into `contract_linking.dart`. Also make sure that both of the devices (your pc which is running ganache as well as your real device which is running flutter application) is connected to the same wifi.

This will fix the issue.

Thanks.

**Comment by mayankpatidar275** [comment]
Thank you very much sir....finally its working because of you. Could you
please explain the importance of changing the server from localhost and why
does it works only on same wifi. Really appreciate your response sir, once
again thank you .

**Comment by anipy1** [comment]
If you use the Android emulator, it works on localhost because the android emulator as well as ganache is running on the same host so you can simply use `http://10.0.2.2:7545`. However, if you're using a real device the `http://10.0.2.2:7545` or `http://127.0.0.1:7545` will not work because localhost means something different on real device, you'll need to configure the RPC SERVER with WiFi as the HOSTNAME and keep your mobile phone and computer on the same network connection.

This is because the library itself does not send signed transactions to miners. Instead, it relies on the RPC client. Our test environment uses a private testnet with ganache. This will give you an RPC endpoint for the library to connect to.

If you want to use your app outside of your local environment you can use public RPC API like [infura](https://infura.io/).

**Comment by mayankpatidar275** [comment]
thanks for explaining sir...
much appreciated
